name: NPM Publish Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    name: Build And Publish Job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: "https://registry.npmjs.org"
      
      - run: npm i
      
      - run: npm run build
      
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}